import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

export const metadata: Metadata = {
  title: "Next Starter App",
  description: "Generated by create next app",
};

const inter = localFont({
  src: "./fonts/Inter-VariableFont_opsz,wght.ttf",
  style: "normal",
  variable: "--font-inter",
  display: "swap",
});

const interItalic = localFont({
  src: "./fonts/Inter-Italic-VariableFont_opsz,wght.ttf",
  style: "italic",
  variable: "--font-inter-italic",
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${interItalic.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
